### PR TITLE
Use Pressable instead of  Button

### PR DESCRIPTION
**Pull request by diego-betto**
Button component is really limited, we usually avoid it and use Pressable to create custom buttons.

Another solution is to use existing libs like

https://callstack.github.io/react-native-paper/docs/guides/theming#dark-theme

https://reactnativeelements.com/docs/customization/theme_object#default-dark-colors

hope it helps, cheers!

### CODE REVIEW

**Comment by gison93** [comment]
Thank you @diego-betto for your help! In the end I was able to solve the dark mode issue with a couple of updates of my phone. Nevertheless thank you for your valuable contribution and for making me learn something new like the use of Pressable!

**Comment by diego-betto** [comment]
I'm happy you solved it!
Well done.

But now I'm curious: software updates or there was some build cache or similar?

**Comment by gison93** [comment]
It was a double software update, the only doubt now it is if it was Android version or Xiaomi version fault!
Anyway I am considering writing a blog post about this. @diego-betto Do you mind me mentioning you and your contribution?

**Comment by diego-betto** [comment]
Ah, ok!
Sure, why not :)

**Pull request merged**
